(() => {
  const app=document.getElementById("app"),scannerDialog=document.getElementById("scannerDialog"),entryDialog=document.getElementById("entryDialog"),sessionDialog=document.getElementById("sessionDialog"),updateDialog=document.getElementById("updateDialog"),video=document.getElementById("scannerVideo"),status=document.getElementById("scannerStatus"),toast=document.getElementById("toast");
  let catalog=Store.catalog(),active=Store.active(),history=Store.history(),settings=Store.settings(),screen="scan";
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const plural=(u,q)=>q===1?u:({stuk:"stuks",doos:"dozen",fles:"flessen",bus:"bussen",set:"sets"}[u]||`${u}s`);
  const showToast=m=>{toast.textContent=m;toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove("show"),2200)};
  const save=()=>{Store.saveCatalog(catalog);Store.saveActive(active);Store.saveHistory(history);Store.saveSettings(settings);render()};
  const footer=()=>`<footer class="app-footer">Ontwikkeld door <strong>${esc(APP_CONFIG.developer)}</strong><br>${esc(APP_CONFIG.name)} · ${esc(APP_CONFIG.version)}</footer>`;
  function nav(){return `<nav class="nav">${[["scan","⌁","Scannen"],["list","☷","Lijst"],["history","◷","Recente scans"],["settings","⚙","Instellingen"]].map(([id,icon,label])=>`<button data-screen="${id}" class="${screen===id?"active":""}"><span class="nav-icon">${icon}</span>${label}</button>`).join("")}</nav>`}
  function listHtml(items){if(!items.length)return`<div class="empty">Nog niets gescand.</div>`;return`<div class="list">${items.map(item=>`<article class="card item"><div><h3>${esc(item.name)}</h3><div class="meta">${esc(item.barcode)}${item.note?` · ${esc(item.note)}`:""}</div></div><div class="badge">${item.quantity} ${esc(plural(item.unit,item.quantity))}</div></article>`).join("")}</div>`}
  function render(){
    app.innerHTML=`<div class="app">
      <header class="topbar"><img class="brand-icon" src="./icons/icon.svg" alt=""><div class="brand-copy"><h1>Van Beijsterveld B.V.</h1><p>Scannen en bestellen</p></div><div class="version">${APP_CONFIG.version}</div></header>
      <section class="screen ${screen==="scan"?"active":""}"><div class="hero"><h2>Nieuwe scan</h2><p>Scan een barcode en voeg het gewenste aantal toe aan de huidige lijst.</p><button class="dark-button" id="openScanner">Barcode scannen</button></div><div class="stats"><div class="card stat"><strong>${active.length}</strong><span>regels in huidige lijst</span></div><div class="card stat"><strong>${Object.keys(catalog).length}</strong><span>bekende artikelen</span></div></div>${footer()}</section>
      <section class="screen ${screen==="list"?"active":""}"><div class="heading"><h2>Huidige lijst</h2><button class="link-button danger" id="clearActive">Leegmaken</button></div>${listHtml(active)}<button class="primary" id="finishSession" style="margin-top:14px">Scanronde afronden</button><button class="secondary" id="emailActive" style="margin-top:9px">Openen in e-mail</button>${footer()}</section>
      <section class="screen ${screen==="history"?"active":""}"><div class="heading"><h2>Recente scans</h2></div>${history.length?`<div class="list">${history.map((s,i)=>`<button class="card history-row" data-history="${i}"><strong>${esc(new Date(s.createdAt).toLocaleString("nl-NL"))}</strong><span>${s.items.length} regels${s.emailedAt?" · e-mail geopend":""}</span></button>`).join("")}</div>`:`<div class="empty">Nog geen afgeronde scanrondes.</div>`}${footer()}</section>
      <section class="screen ${screen==="settings"?"active":""}"><div class="heading"><h2>Instellingen</h2></div><div class="card settings-group"><div><strong>E-mailadressen</strong><div class="small">Deze worden ingevuld wanneer je een lijst in jouw mailapp opent.</div></div><div id="emailRows">${settings.emails.map((email,i)=>`<div class="email-row"><input type="email" value="${esc(email)}" data-email-index="${i}" placeholder="inkoop@bedrijf.nl"><button data-remove-email="${i}">×</button></div>`).join("")}</div><button class="secondary" id="addEmail">E-mailadres toevoegen</button><button class="primary" id="saveSettings">Instellingen opslaan</button></div>
      <div class="card about-card"><img class="about-logo" src="./icons/icon.svg" alt=""><div class="about-title">Van Beijsterveld B.V.</div><div class="about-subtitle">Scannen en bestellen</div><div class="about-divider"></div><div class="credit">Ontwikkeld door <strong>${esc(APP_CONFIG.developer)}</strong><br>Versie ${esc(APP_CONFIG.version)}<br>Build ${esc(APP_CONFIG.build)}</div></div></section>
      ${nav()}</div>`}
  function openEntry(code){document.getElementById("entryForm").reset();document.getElementById("quantity").value=1;document.getElementById("barcode").value=code;const known=catalog[code];document.getElementById("entryTitle").textContent=known?"Hoeveel wil je bestellen?":"Nieuwe barcode";document.getElementById("entryNotice").textContent=known?"Dit artikel is herkend.":"Vul voorlopig een artikelnaam en eenheid in.";document.getElementById("productName").value=known?.name||"";document.getElementById("unit").value=known?.unit||"stuk";document.getElementById("note").value="";entryDialog.showModal()}
  async function startScanner(){scannerDialog.showModal();status.textContent="Camera starten.";try{await Scanner.start(video,code=>{scannerDialog.close();openEntry(code)},text=>status.textContent=text)}catch(error){status.textContent=error.message==="library"?"De scanner kon niet worden geladen. Controleer internet en ververs de app.":"De camera kon niet worden geopend. Controleer de cameratoestemming."}}
  function mailText(items,date=new Date()){const lines=items.map((x,i)=>`${i+1}. ${x.name}, ${x.quantity} ${plural(x.unit,x.quantity)}${x.note?`, ${x.note}`:""}`);return`Bestellijst Van Beijsterveld B.V.\n\n${lines.join("\n")}\n\nAangemaakt op ${date.toLocaleString("nl-NL")}.`}
  function openEmail(items,date=new Date()){if(!items.length)return showToast("De lijst is leeg.");const recipients=settings.emails.filter(Boolean).join(","),subject=encodeURIComponent(`Bestellijst Van Beijsterveld B.V. ${date.toLocaleDateString("nl-NL")}`),body=encodeURIComponent(mailText(items,date));location.href=`mailto:${recipients}?subject=${subject}&body=${body}`}
  app.addEventListener("click",e=>{const b=e.target.closest("[data-screen]");if(b){screen=b.dataset.screen;render();return}if(e.target.id==="openScanner")startScanner();if(e.target.id==="clearActive"&&active.length&&confirm("Huidige lijst leegmaken?")){active=[];save()}if(e.target.id==="emailActive")openEmail(active);if(e.target.id==="finishSession"){if(!active.length)return showToast("De lijst is leeg.");history.unshift({id:crypto.randomUUID?.()||String(Date.now()),createdAt:new Date().toISOString(),items:structuredClone(active)});active=[];save();screen="history";render();showToast("Scanronde opgeslagen.")}if(e.target.dataset.history!==undefined){const s=history[Number(e.target.dataset.history)];document.getElementById("sessionTitle").textContent=new Date(s.createdAt).toLocaleString("nl-NL");document.getElementById("sessionDetail").innerHTML=`${listHtml(s.items)}<button class="primary" id="emailHistory" style="margin-top:13px">Opnieuw openen in e-mail</button>`;document.getElementById("emailHistory").onclick=()=>openEmail(s.items,new Date(s.createdAt));sessionDialog.showModal()}if(e.target.id==="addEmail"){settings.emails.push("");save();screen="settings";render()}if(e.target.dataset.removeEmail!==undefined){settings.emails.splice(Number(e.target.dataset.removeEmail),1);if(!settings.emails.length)settings.emails=[""];save();screen="settings";render()}if(e.target.id==="saveSettings"){document.querySelectorAll("[data-email-index]").forEach(input=>settings.emails[Number(input.dataset.emailIndex)]=input.value.trim());settings.emails=settings.emails.filter(Boolean);if(!settings.emails.length)settings.emails=[""];save();screen="settings";render();showToast("Instellingen opgeslagen.")}});
  document.querySelector("[data-close-scanner]").onclick=()=>{Scanner.stop();scannerDialog.close()};document.querySelector("[data-close-entry]").onclick=()=>entryDialog.close();document.querySelector("[data-close-session]").onclick=()=>sessionDialog.close();document.getElementById("manualBarcode").onclick=()=>{Scanner.stop();scannerDialog.close();const code=prompt("Voer de barcode in.");if(code?.trim())openEntry(code.trim())};
  document.getElementById("entryForm").onsubmit=e=>{e.preventDefault();const item={barcode:document.getElementById("barcode").value.trim(),name:document.getElementById("productName").value.trim(),quantity:Math.max(1,Number(document.getElementById("quantity").value)||1),unit:document.getElementById("unit").value,note:document.getElementById("note").value.trim()};catalog[item.barcode]={name:item.name,unit:item.unit};const existing=active.find(x=>x.barcode===item.barcode&&x.unit===item.unit&&x.note===item.note);existing?existing.quantity+=item.quantity:active.push(item);entryDialog.close();save();showToast("Artikel toegevoegd.")};
  document.getElementById("updateLater").onclick=()=>updateDialog.close();document.getElementById("updateNow").onclick=()=>Updates.apply();Updates.init(()=>{if(!updateDialog.open)updateDialog.showModal()}).catch(()=>{});render()
})();